# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Konrad Heimel
---
apiVersion: kollect.dev/v1alpha1
kind: KollectInventory
metadata:
  name: team-inventory
  namespace: default
spec:
  sinkRefs: []
