sonar.projectKey=platformrelay_kollect
sonar.organization=platformrelay
sonar.projectName=kollect
sonar.sources=.
sonar.exclusions=**/zz_generated.*,**/vendor/**,**/ui/**,**/charts/**,**/hack/**,**/test/**,**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=**/api/**,**/cmd/**,**/test/**
