---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollectclusterinventory
  failurePolicy: Fail
  name: vkollectclusterinventory.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollectclusterinventories
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollectclusterscope
  failurePolicy: Fail
  name: vkollectclusterscope.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollectclusterscopes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollectclustertarget
  failurePolicy: Fail
  name: vkollectclustertarget.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollectclustertargets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollectconnectiontest
  failurePolicy: Fail
  name: vkollectconnectiontest.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollectconnectiontests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollectdatabasesink
  failurePolicy: Fail
  name: vkollectdatabasesink.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollectdatabasesinks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollecteventsink
  failurePolicy: Fail
  name: vkollecteventsink.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollecteventsinks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollectinventory
  failurePolicy: Fail
  name: vkollectinventory.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollectinventories
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollectprofile
  failurePolicy: Fail
  name: vkollectprofile.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollectprofiles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollectscope
  failurePolicy: Fail
  name: vkollectscope.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollectscopes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollectsnapshotsink
  failurePolicy: Fail
  name: vkollectsnapshotsink.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollectsnapshotsinks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kollect-dev-v1alpha1-kollecttarget
  failurePolicy: Fail
  name: vkollecttarget.kb.io
  rules:
  - apiGroups:
    - kollect.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kollecttargets
  sideEffects: None
