{{- if and .Values.rbac.create (not .Values.tenantMode) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kollect.fullname" . }}-manager
  labels:
    {{- include "kollect.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [configmaps, namespaces, secrets]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [services]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [authentication.k8s.io]
    resources: [tokenreviews]
    verbs: [create]
  - apiGroups: [authorization.k8s.io]
    resources: [selfsubjectaccessreviews, subjectaccessreviews]
    verbs: [create]
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [kollect.dev]
    resources:
      - kollectclusterinventories
      - kollectclustertargets
      - kollectconnectiontests
      - kollectinventories
      - kollectremoteclusters
      - kollectclustersnapshotsinks
      - kollectclusterdatabasesinks
      - kollectclustereventsinks
      - kollectdatabasesinks
      - kollecteventsinks
      - kollectsnapshotsinks
      - kollecttargets
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [kollect.dev]
    resources:
      - kollectclusterinventories/finalizers
      - kollectclustertargets/finalizers
      - kollectinventories/finalizers
      - kollectremoteclusters/finalizers
      - kollecttargets/finalizers
    verbs: [update]
  - apiGroups: [kollect.dev]
    resources:
      - kollectclusterinventories/status
      - kollectclustertargets/status
      - kollectconnectiontests/status
      - kollectinventories/status
      - kollectremoteclusters/status
      - kollectclustersnapshotsinks/status
      - kollectclusterdatabasesinks/status
      - kollectclustereventsinks/status
      - kollectdatabasesinks/status
      - kollecteventsinks/status
      - kollectsnapshotsinks/status
      - kollecttargets/status
    verbs: [get, patch, update]
  - apiGroups: [kollect.dev]
    resources: [kollectclusterprofiles, kollectprofiles, kollectscopes]
    verbs: [get, list, watch]
  - apiGroups: [cert-manager.io]
    resources: [certificates]
    verbs: [get, list, watch]
{{- end }}
