---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - kollect.dev
  resources:
  - kollectclusterdatabasesinks
  - kollectclustereventsinks
  - kollectclusterinventories
  - kollectclustersnapshotsinks
  - kollectclustertargets
  - kollectconnectiontests
  - kollectdatabasesinks
  - kollecteventsinks
  - kollectinventories
  - kollectremoteclusters
  - kollectsnapshotsinks
  - kollecttargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kollect.dev
  resources:
  - kollectclusterdatabasesinks/status
  - kollectclustereventsinks/status
  - kollectclusterinventories/status
  - kollectclustersnapshotsinks/status
  - kollectclustertargets/status
  - kollectconnectiontests/status
  - kollectdatabasesinks/status
  - kollecteventsinks/status
  - kollectinventories/status
  - kollectremoteclusters/status
  - kollectsnapshotsinks/status
  - kollecttargets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kollect.dev
  resources:
  - kollectclusterinventories/finalizers
  - kollectclustertargets/finalizers
  - kollectinventories/finalizers
  - kollectremoteclusters/finalizers
  - kollecttargets/finalizers
  verbs:
  - update
- apiGroups:
  - kollect.dev
  resources:
  - kollectclusterprofiles
  - kollectprofiles
  - kollectscopes
  - kollectsinks
  verbs:
  - get
  - list
  - watch
