---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - kollect.dev
  resources:
  - kollecthubs
  - kollectinventories
  - kollectremoteclusters
  - kollectsinks
  - kollecttargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kollect.dev
  resources:
  - kollecthubs/finalizers
  - kollectinventories/finalizers
  - kollectremoteclusters/finalizers
  - kollecttargets/finalizers
  verbs:
  - update
- apiGroups:
  - kollect.dev
  resources:
  - kollecthubs/status
  - kollectinventories/status
  - kollectremoteclusters/status
  - kollectsinks/status
  - kollecttargets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kollect.dev
  resources:
  - kollectprofiles
  - kollectscopes
  verbs:
  - get
  - list
  - watch
