apiVersion: kollect.dev/v1alpha1
kind: KollectTarget
metadata:
  name: team-argo-applications
  namespace: default
  labels:
    app.kubernetes.io/name: kollect
    app.kubernetes.io/managed-by: kustomize
spec:
  profileRef: argo-application-summary
  namespaceSelector:
    matchLabels:
      argocd.argoproj.io/instance: team-a
  suspend: false
