apiVersion: kollect.dev/v1alpha1
kind: KollectClusterTarget
metadata:
  name: platform-argo-applications
spec:
  profileRef:
    name: argo-application-summary
    namespace: kollect-system
  namespaceSelector:
    matchLabels:
      kollect.dev/tenant: platform
