## Append samples of your project ##
resources:
- kollect_v1alpha1_kollectprofile.yaml
- kollect_v1alpha1_kollectprofile_service-endpoints.yaml
- kollect_v1alpha1_kollectprofile_ingress-hosts.yaml
- kollect_v1alpha1_kollectprofile_helm-release-summary.yaml
- kollect_v1alpha1_kollectprofile_helm-release-values-redacted.yaml
- kollect_v1alpha1_kollectprofile_argo-application-summary.yaml
- kollect_v1alpha1_kollectsnapshotsink.yaml
- kollect_v1alpha1_kollectdatabasesink.yaml
- kollect_v1alpha1_kollecteventsink_kafka.yaml
- kollect_v1alpha1_kollecttarget.yaml
- kollect_v1alpha1_kollecttarget_opt-in.yaml
- kollect_v1alpha1_kollecttarget_helm-releases.yaml
- kollect_v1alpha1_kollecttarget_argo-applications.yaml
- kollect_v1alpha1_kollectinventory.yaml
- kollect_v1alpha1_kollectscope_team-a.yaml
- kollect_v1alpha1_kollectconnectiontest.yaml
- kollect_v1alpha1_kollectclusterprofile.yaml
- kollect_v1alpha1_kollectclustertarget.yaml
- kollect_v1alpha1_kollectclusterinventory.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
