## Append samples of your project ##
resources:
- kollect_v1alpha1_kollectprofile.yaml
- kollect_v1alpha1_kollectsink.yaml
- kollect_v1alpha1_kollecttarget.yaml
- kollect_v1alpha1_kollectinventory.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
