apiVersion: kollect.dev/v1alpha1
kind: KollectTarget
metadata:
  labels:
    app.kubernetes.io/name: kollect
    app.kubernetes.io/managed-by: kustomize
  name: kollecttarget-sample
spec:
  # TODO(user): Add fields here
