apiVersion: kollect.dev/v1alpha1
kind: KollectProfile
metadata:
  labels:
    app.kubernetes.io/name: kollect
    app.kubernetes.io/managed-by: kustomize
  name: kollectprofile-sample
spec:
  # TODO(user): Add fields here
