//go:build !ignore_autogenerated

// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Konrad Heimel

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeSpec) DeepCopyInto(out *AttributeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeSpec.
func (in *AttributeSpec) DeepCopy() *AttributeSpec {
	if in == nil {
		return nil
	}
	out := new(AttributeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQuerySpec) DeepCopyInto(out *BigQuerySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQuerySpec.
func (in *BigQuerySpec) DeepCopy() *BigQuerySpec {
	if in == nil {
		return nil
	}
	out := new(BigQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionFilterSpec) DeepCopyInto(out *CollectionFilterSpec) {
	*out = *in
	if in.IncludedNamespaces != nil {
		in, out := &in.IncludedNamespaces, &out.IncludedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedNamespaces != nil {
		in, out := &in.ExcludedNamespaces, &out.ExcludedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceExcludeSelector != nil {
		in, out := &in.NamespaceExcludeSelector, &out.NamespaceExcludeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceRules != nil {
		in, out := &in.ResourceRules, &out.ResourceRules
		*out = make([]ResourceRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionFilterSpec.
func (in *CollectionFilterSpec) DeepCopy() *CollectionFilterSpec {
	if in == nil {
		return nil
	}
	out := new(CollectionFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionFilterStatus) DeepCopyInto(out *CollectionFilterStatus) {
	*out = *in
	if in.MatchedNamespaces != nil {
		in, out := &in.MatchedNamespaces, &out.MatchedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EffectiveNamespaces != nil {
		in, out := &in.EffectiveNamespaces, &out.EffectiveNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionFilterStatus.
func (in *CollectionFilterStatus) DeepCopy() *CollectionFilterStatus {
	if in == nil {
		return nil
	}
	out := new(CollectionFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTestSinkRef) DeepCopyInto(out *ConnectionTestSinkRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTestSinkRef.
func (in *ConnectionTestSinkRef) DeepCopy() *ConnectionTestSinkRef {
	if in == nil {
		return nil
	}
	out := new(ConnectionTestSinkRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportSpec) DeepCopyInto(out *ExportSpec) {
	*out = *in
	if in.DedupeIdentity != nil {
		in, out := &in.DedupeIdentity, &out.DedupeIdentity
		*out = new(bool)
		**out = **in
	}
	if in.Prune != nil {
		in, out := &in.Prune, &out.Prune
		*out = new(PruneSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportSpec.
func (in *ExportSpec) DeepCopy() *ExportSpec {
	if in == nil {
		return nil
	}
	out := new(ExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FamilySinkStatus) DeepCopyInto(out *FamilySinkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Preview != nil {
		in, out := &in.Preview, &out.Preview
		*out = new(SinkPreviewStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FamilySinkStatus.
func (in *FamilySinkStatus) DeepCopy() *FamilySinkStatus {
	if in == nil {
		return nil
	}
	out := new(FamilySinkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitAuthSpec) DeepCopyInto(out *GitAuthSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitAuthSpec.
func (in *GitAuthSpec) DeepCopy() *GitAuthSpec {
	if in == nil {
		return nil
	}
	out := new(GitAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitAuthorSpec) DeepCopyInto(out *GitAuthorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitAuthorSpec.
func (in *GitAuthorSpec) DeepCopy() *GitAuthorSpec {
	if in == nil {
		return nil
	}
	out := new(GitAuthorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitLabSpec) DeepCopyInto(out *GitLabSpec) {
	*out = *in
	if in.MergeRequest != nil {
		in, out := &in.MergeRequest, &out.MergeRequest
		*out = new(MergeRequestSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitLabSpec.
func (in *GitLabSpec) DeepCopy() *GitLabSpec {
	if in == nil {
		return nil
	}
	out := new(GitLabSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitPreviewStatus) DeepCopyInto(out *GitPreviewStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitPreviewStatus.
func (in *GitPreviewStatus) DeepCopy() *GitPreviewStatus {
	if in == nil {
		return nil
	}
	out := new(GitPreviewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitSpec) DeepCopyInto(out *GitSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(GitAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CommitTrailers != nil {
		in, out := &in.CommitTrailers, &out.CommitTrailers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Author != nil {
		in, out := &in.Author, &out.Author
		*out = new(GitAuthorSpec)
		**out = **in
	}
	if in.CloneDepth != nil {
		in, out := &in.CloneDepth, &out.CloneDepth
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitSpec.
func (in *GitSpec) DeepCopy() *GitSpec {
	if in == nil {
		return nil
	}
	out := new(GitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupVersionKind) DeepCopyInto(out *GroupVersionKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupVersionKind.
func (in *GroupVersionKind) DeepCopy() *GroupVersionKind {
	if in == nil {
		return nil
	}
	out := new(GroupVersionKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPEndpointConfig) DeepCopyInto(out *HTTPEndpointConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPEndpointConfig.
func (in *HTTPEndpointConfig) DeepCopy() *HTTPEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSinkSpec) DeepCopyInto(out *HTTPSinkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSinkSpec.
func (in *HTTPSinkSpec) DeepCopy() *HTTPSinkSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventorySinkBinding) DeepCopyInto(out *InventorySinkBinding) {
	*out = *in
	in.Ref.DeepCopyInto(&out.Ref)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventorySinkBinding.
func (in *InventorySinkBinding) DeepCopy() *InventorySinkBinding {
	if in == nil {
		return nil
	}
	out := new(InventorySinkBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventorySinkExportStatus) DeepCopyInto(out *InventorySinkExportStatus) {
	*out = *in
	if in.LastExportTime != nil {
		in, out := &in.LastExportTime, &out.LastExportTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventorySinkExportStatus.
func (in *InventorySinkExportStatus) DeepCopy() *InventorySinkExportStatus {
	if in == nil {
		return nil
	}
	out := new(InventorySinkExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventorySinkRef) DeepCopyInto(out *InventorySinkRef) {
	*out = *in
	if in.ExportMinInterval != nil {
		in, out := &in.ExportMinInterval, &out.ExportMinInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventorySinkRef.
func (in *InventorySinkRef) DeepCopy() *InventorySinkRef {
	if in == nil {
		return nil
	}
	out := new(InventorySinkRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in InventorySinkRefList) DeepCopyInto(out *InventorySinkRefList) {
	{
		in := &in
		*out = make(InventorySinkRefList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventorySinkRefList.
func (in InventorySinkRefList) DeepCopy() InventorySinkRefList {
	if in == nil {
		return nil
	}
	out := new(InventorySinkRefList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaPreviewStatus) DeepCopyInto(out *KafkaPreviewStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaPreviewStatus.
func (in *KafkaPreviewStatus) DeepCopy() *KafkaPreviewStatus {
	if in == nil {
		return nil
	}
	out := new(KafkaPreviewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSpec) DeepCopyInto(out *KafkaSpec) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSpec.
func (in *KafkaSpec) DeepCopy() *KafkaSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterDatabaseSink) DeepCopyInto(out *KollectClusterDatabaseSink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterDatabaseSink.
func (in *KollectClusterDatabaseSink) DeepCopy() *KollectClusterDatabaseSink {
	if in == nil {
		return nil
	}
	out := new(KollectClusterDatabaseSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterDatabaseSink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterDatabaseSinkList) DeepCopyInto(out *KollectClusterDatabaseSinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectClusterDatabaseSink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterDatabaseSinkList.
func (in *KollectClusterDatabaseSinkList) DeepCopy() *KollectClusterDatabaseSinkList {
	if in == nil {
		return nil
	}
	out := new(KollectClusterDatabaseSinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterDatabaseSinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterEventSink) DeepCopyInto(out *KollectClusterEventSink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterEventSink.
func (in *KollectClusterEventSink) DeepCopy() *KollectClusterEventSink {
	if in == nil {
		return nil
	}
	out := new(KollectClusterEventSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterEventSink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterEventSinkList) DeepCopyInto(out *KollectClusterEventSinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectClusterEventSink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterEventSinkList.
func (in *KollectClusterEventSinkList) DeepCopy() *KollectClusterEventSinkList {
	if in == nil {
		return nil
	}
	out := new(KollectClusterEventSinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterEventSinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterInventory) DeepCopyInto(out *KollectClusterInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterInventory.
func (in *KollectClusterInventory) DeepCopy() *KollectClusterInventory {
	if in == nil {
		return nil
	}
	out := new(KollectClusterInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterInventoryList) DeepCopyInto(out *KollectClusterInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectClusterInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterInventoryList.
func (in *KollectClusterInventoryList) DeepCopy() *KollectClusterInventoryList {
	if in == nil {
		return nil
	}
	out := new(KollectClusterInventoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterInventorySpec) DeepCopyInto(out *KollectClusterInventorySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TargetSelector != nil {
		in, out := &in.TargetSelector, &out.TargetSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotSinkRefs != nil {
		in, out := &in.SnapshotSinkRefs, &out.SnapshotSinkRefs
		*out = make(InventorySinkRefList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DatabaseSinkRefs != nil {
		in, out := &in.DatabaseSinkRefs, &out.DatabaseSinkRefs
		*out = make(InventorySinkRefList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EventSinkRefs != nil {
		in, out := &in.EventSinkRefs, &out.EventSinkRefs
		*out = make(InventorySinkRefList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExportMinInterval != nil {
		in, out := &in.ExportMinInterval, &out.ExportMinInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterInventorySpec.
func (in *KollectClusterInventorySpec) DeepCopy() *KollectClusterInventorySpec {
	if in == nil {
		return nil
	}
	out := new(KollectClusterInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterInventoryStatus) DeepCopyInto(out *KollectClusterInventoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastExportTime != nil {
		in, out := &in.LastExportTime, &out.LastExportTime
		*out = (*in).DeepCopy()
	}
	if in.SinkExports != nil {
		in, out := &in.SinkExports, &out.SinkExports
		*out = make([]InventorySinkExportStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterInventoryStatus.
func (in *KollectClusterInventoryStatus) DeepCopy() *KollectClusterInventoryStatus {
	if in == nil {
		return nil
	}
	out := new(KollectClusterInventoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterProfile) DeepCopyInto(out *KollectClusterProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterProfile.
func (in *KollectClusterProfile) DeepCopy() *KollectClusterProfile {
	if in == nil {
		return nil
	}
	out := new(KollectClusterProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterProfileList) DeepCopyInto(out *KollectClusterProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectClusterProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterProfileList.
func (in *KollectClusterProfileList) DeepCopy() *KollectClusterProfileList {
	if in == nil {
		return nil
	}
	out := new(KollectClusterProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterProfileSpec) DeepCopyInto(out *KollectClusterProfileSpec) {
	*out = *in
	out.TargetGVK = in.TargetGVK
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]AttributeSpec, len(*in))
		copy(*out, *in)
	}
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = new(ExportSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterProfileSpec.
func (in *KollectClusterProfileSpec) DeepCopy() *KollectClusterProfileSpec {
	if in == nil {
		return nil
	}
	out := new(KollectClusterProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterProfileStatus) DeepCopyInto(out *KollectClusterProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterProfileStatus.
func (in *KollectClusterProfileStatus) DeepCopy() *KollectClusterProfileStatus {
	if in == nil {
		return nil
	}
	out := new(KollectClusterProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterScope) DeepCopyInto(out *KollectClusterScope) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterScope.
func (in *KollectClusterScope) DeepCopy() *KollectClusterScope {
	if in == nil {
		return nil
	}
	out := new(KollectClusterScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterScope) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterScopeList) DeepCopyInto(out *KollectClusterScopeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectClusterScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterScopeList.
func (in *KollectClusterScopeList) DeepCopy() *KollectClusterScopeList {
	if in == nil {
		return nil
	}
	out := new(KollectClusterScopeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterScopeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterScopeSpec) DeepCopyInto(out *KollectClusterScopeSpec) {
	*out = *in
	in.ScopeCeilingSpec.DeepCopyInto(&out.ScopeCeilingSpec)
	if in.SnapshotSinkRefs != nil {
		in, out := &in.SnapshotSinkRefs, &out.SnapshotSinkRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DatabaseSinkRefs != nil {
		in, out := &in.DatabaseSinkRefs, &out.DatabaseSinkRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EventSinkRefs != nil {
		in, out := &in.EventSinkRefs, &out.EventSinkRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterScopeSpec.
func (in *KollectClusterScopeSpec) DeepCopy() *KollectClusterScopeSpec {
	if in == nil {
		return nil
	}
	out := new(KollectClusterScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterSnapshotSink) DeepCopyInto(out *KollectClusterSnapshotSink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterSnapshotSink.
func (in *KollectClusterSnapshotSink) DeepCopy() *KollectClusterSnapshotSink {
	if in == nil {
		return nil
	}
	out := new(KollectClusterSnapshotSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterSnapshotSink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterSnapshotSinkList) DeepCopyInto(out *KollectClusterSnapshotSinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectClusterSnapshotSink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterSnapshotSinkList.
func (in *KollectClusterSnapshotSinkList) DeepCopy() *KollectClusterSnapshotSinkList {
	if in == nil {
		return nil
	}
	out := new(KollectClusterSnapshotSinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterSnapshotSinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterTarget) DeepCopyInto(out *KollectClusterTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterTarget.
func (in *KollectClusterTarget) DeepCopy() *KollectClusterTarget {
	if in == nil {
		return nil
	}
	out := new(KollectClusterTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterTargetList) DeepCopyInto(out *KollectClusterTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectClusterTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterTargetList.
func (in *KollectClusterTargetList) DeepCopy() *KollectClusterTargetList {
	if in == nil {
		return nil
	}
	out := new(KollectClusterTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectClusterTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterTargetSpec) DeepCopyInto(out *KollectClusterTargetSpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.CollectionFilterSpec.DeepCopyInto(&out.CollectionFilterSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterTargetSpec.
func (in *KollectClusterTargetSpec) DeepCopy() *KollectClusterTargetSpec {
	if in == nil {
		return nil
	}
	out := new(KollectClusterTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectClusterTargetStatus) DeepCopyInto(out *KollectClusterTargetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CollectionFilterStatus.DeepCopyInto(&out.CollectionFilterStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectClusterTargetStatus.
func (in *KollectClusterTargetStatus) DeepCopy() *KollectClusterTargetStatus {
	if in == nil {
		return nil
	}
	out := new(KollectClusterTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectConnectionTest) DeepCopyInto(out *KollectConnectionTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectConnectionTest.
func (in *KollectConnectionTest) DeepCopy() *KollectConnectionTest {
	if in == nil {
		return nil
	}
	out := new(KollectConnectionTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectConnectionTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectConnectionTestList) DeepCopyInto(out *KollectConnectionTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectConnectionTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectConnectionTestList.
func (in *KollectConnectionTestList) DeepCopy() *KollectConnectionTestList {
	if in == nil {
		return nil
	}
	out := new(KollectConnectionTestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectConnectionTestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectConnectionTestSpec) DeepCopyInto(out *KollectConnectionTestSpec) {
	*out = *in
	out.SinkRef = in.SinkRef
	if in.OwnerSink != nil {
		in, out := &in.OwnerSink, &out.OwnerSink
		*out = new(bool)
		**out = **in
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectConnectionTestSpec.
func (in *KollectConnectionTestSpec) DeepCopy() *KollectConnectionTestSpec {
	if in == nil {
		return nil
	}
	out := new(KollectConnectionTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectConnectionTestStatus) DeepCopyInto(out *KollectConnectionTestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectConnectionTestStatus.
func (in *KollectConnectionTestStatus) DeepCopy() *KollectConnectionTestStatus {
	if in == nil {
		return nil
	}
	out := new(KollectConnectionTestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectDatabaseSink) DeepCopyInto(out *KollectDatabaseSink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectDatabaseSink.
func (in *KollectDatabaseSink) DeepCopy() *KollectDatabaseSink {
	if in == nil {
		return nil
	}
	out := new(KollectDatabaseSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectDatabaseSink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectDatabaseSinkList) DeepCopyInto(out *KollectDatabaseSinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectDatabaseSink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectDatabaseSinkList.
func (in *KollectDatabaseSinkList) DeepCopy() *KollectDatabaseSinkList {
	if in == nil {
		return nil
	}
	out := new(KollectDatabaseSinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectDatabaseSinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectDatabaseSinkSpec) DeepCopyInto(out *KollectDatabaseSinkSpec) {
	*out = *in
	in.SinkCommonFields.DeepCopyInto(&out.SinkCommonFields)
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BigQuery != nil {
		in, out := &in.BigQuery, &out.BigQuery
		*out = new(BigQuerySpec)
		**out = **in
	}
	if in.MongoDB != nil {
		in, out := &in.MongoDB, &out.MongoDB
		*out = new(MongoSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectDatabaseSinkSpec.
func (in *KollectDatabaseSinkSpec) DeepCopy() *KollectDatabaseSinkSpec {
	if in == nil {
		return nil
	}
	out := new(KollectDatabaseSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectEventSink) DeepCopyInto(out *KollectEventSink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectEventSink.
func (in *KollectEventSink) DeepCopy() *KollectEventSink {
	if in == nil {
		return nil
	}
	out := new(KollectEventSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectEventSink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectEventSinkList) DeepCopyInto(out *KollectEventSinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectEventSink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectEventSinkList.
func (in *KollectEventSinkList) DeepCopy() *KollectEventSinkList {
	if in == nil {
		return nil
	}
	out := new(KollectEventSinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectEventSinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectEventSinkSpec) DeepCopyInto(out *KollectEventSinkSpec) {
	*out = *in
	in.SinkCommonFields.DeepCopyInto(&out.SinkCommonFields)
	if in.Nats != nil {
		in, out := &in.Nats, &out.Nats
		*out = new(NatsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectEventSinkSpec.
func (in *KollectEventSinkSpec) DeepCopy() *KollectEventSinkSpec {
	if in == nil {
		return nil
	}
	out := new(KollectEventSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectInventory) DeepCopyInto(out *KollectInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectInventory.
func (in *KollectInventory) DeepCopy() *KollectInventory {
	if in == nil {
		return nil
	}
	out := new(KollectInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectInventoryList) DeepCopyInto(out *KollectInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectInventoryList.
func (in *KollectInventoryList) DeepCopy() *KollectInventoryList {
	if in == nil {
		return nil
	}
	out := new(KollectInventoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectInventorySpec) DeepCopyInto(out *KollectInventorySpec) {
	*out = *in
	if in.SnapshotSinkRefs != nil {
		in, out := &in.SnapshotSinkRefs, &out.SnapshotSinkRefs
		*out = make(InventorySinkRefList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DatabaseSinkRefs != nil {
		in, out := &in.DatabaseSinkRefs, &out.DatabaseSinkRefs
		*out = make(InventorySinkRefList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EventSinkRefs != nil {
		in, out := &in.EventSinkRefs, &out.EventSinkRefs
		*out = make(InventorySinkRefList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExportMinInterval != nil {
		in, out := &in.ExportMinInterval, &out.ExportMinInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxExportBytes != nil {
		in, out := &in.MaxExportBytes, &out.MaxExportBytes
		*out = new(int64)
		**out = **in
	}
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(HTTPEndpointConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectInventorySpec.
func (in *KollectInventorySpec) DeepCopy() *KollectInventorySpec {
	if in == nil {
		return nil
	}
	out := new(KollectInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectInventoryStatus) DeepCopyInto(out *KollectInventoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastExportTime != nil {
		in, out := &in.LastExportTime, &out.LastExportTime
		*out = (*in).DeepCopy()
	}
	if in.SinkExports != nil {
		in, out := &in.SinkExports, &out.SinkExports
		*out = make([]InventorySinkExportStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectInventoryStatus.
func (in *KollectInventoryStatus) DeepCopy() *KollectInventoryStatus {
	if in == nil {
		return nil
	}
	out := new(KollectInventoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectProfile) DeepCopyInto(out *KollectProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectProfile.
func (in *KollectProfile) DeepCopy() *KollectProfile {
	if in == nil {
		return nil
	}
	out := new(KollectProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectProfileList) DeepCopyInto(out *KollectProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectProfileList.
func (in *KollectProfileList) DeepCopy() *KollectProfileList {
	if in == nil {
		return nil
	}
	out := new(KollectProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectProfileSpec) DeepCopyInto(out *KollectProfileSpec) {
	*out = *in
	out.TargetGVK = in.TargetGVK
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]AttributeSpec, len(*in))
		copy(*out, *in)
	}
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = new(ExportSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectProfileSpec.
func (in *KollectProfileSpec) DeepCopy() *KollectProfileSpec {
	if in == nil {
		return nil
	}
	out := new(KollectProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectProfileStatus) DeepCopyInto(out *KollectProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectProfileStatus.
func (in *KollectProfileStatus) DeepCopy() *KollectProfileStatus {
	if in == nil {
		return nil
	}
	out := new(KollectProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectScope) DeepCopyInto(out *KollectScope) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectScope.
func (in *KollectScope) DeepCopy() *KollectScope {
	if in == nil {
		return nil
	}
	out := new(KollectScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectScope) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectScopeList) DeepCopyInto(out *KollectScopeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectScopeList.
func (in *KollectScopeList) DeepCopy() *KollectScopeList {
	if in == nil {
		return nil
	}
	out := new(KollectScopeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectScopeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectScopeSpec) DeepCopyInto(out *KollectScopeSpec) {
	*out = *in
	in.ScopeCeilingSpec.DeepCopyInto(&out.ScopeCeilingSpec)
	if in.SnapshotSinkRefs != nil {
		in, out := &in.SnapshotSinkRefs, &out.SnapshotSinkRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DatabaseSinkRefs != nil {
		in, out := &in.DatabaseSinkRefs, &out.DatabaseSinkRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EventSinkRefs != nil {
		in, out := &in.EventSinkRefs, &out.EventSinkRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectScopeSpec.
func (in *KollectScopeSpec) DeepCopy() *KollectScopeSpec {
	if in == nil {
		return nil
	}
	out := new(KollectScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectSinkSpec) DeepCopyInto(out *KollectSinkSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionTest != nil {
		in, out := &in.ConnectionTest, &out.ConnectionTest
		*out = new(bool)
		**out = **in
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MongoDB != nil {
		in, out := &in.MongoDB, &out.MongoDB
		*out = new(MongoSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Nats != nil {
		in, out := &in.Nats, &out.Nats
		*out = new(NatsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectStore != nil {
		in, out := &in.ObjectStore, &out.ObjectStore
		*out = new(ObjectStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GitLab != nil {
		in, out := &in.GitLab, &out.GitLab
		*out = new(GitLabSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExportMinInterval != nil {
		in, out := &in.ExportMinInterval, &out.ExportMinInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Serialization != nil {
		in, out := &in.Serialization, &out.Serialization
		*out = new(SerializationSpec)
		**out = **in
	}
	if in.Layout != nil {
		in, out := &in.Layout, &out.Layout
		*out = new(LayoutSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Provisioning != nil {
		in, out := &in.Provisioning, &out.Provisioning
		*out = new(ProvisioningSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectSinkSpec.
func (in *KollectSinkSpec) DeepCopy() *KollectSinkSpec {
	if in == nil {
		return nil
	}
	out := new(KollectSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectSnapshotSink) DeepCopyInto(out *KollectSnapshotSink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectSnapshotSink.
func (in *KollectSnapshotSink) DeepCopy() *KollectSnapshotSink {
	if in == nil {
		return nil
	}
	out := new(KollectSnapshotSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectSnapshotSink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectSnapshotSinkList) DeepCopyInto(out *KollectSnapshotSinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectSnapshotSink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectSnapshotSinkList.
func (in *KollectSnapshotSinkList) DeepCopy() *KollectSnapshotSinkList {
	if in == nil {
		return nil
	}
	out := new(KollectSnapshotSinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectSnapshotSinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectSnapshotSinkSpec) DeepCopyInto(out *KollectSnapshotSinkSpec) {
	*out = *in
	in.SinkCommonFields.DeepCopyInto(&out.SinkCommonFields)
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GitLab != nil {
		in, out := &in.GitLab, &out.GitLab
		*out = new(GitLabSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectStore != nil {
		in, out := &in.ObjectStore, &out.ObjectStore
		*out = new(ObjectStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPSinkSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectSnapshotSinkSpec.
func (in *KollectSnapshotSinkSpec) DeepCopy() *KollectSnapshotSinkSpec {
	if in == nil {
		return nil
	}
	out := new(KollectSnapshotSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectTarget) DeepCopyInto(out *KollectTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectTarget.
func (in *KollectTarget) DeepCopy() *KollectTarget {
	if in == nil {
		return nil
	}
	out := new(KollectTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectTargetList) DeepCopyInto(out *KollectTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KollectTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectTargetList.
func (in *KollectTargetList) DeepCopy() *KollectTargetList {
	if in == nil {
		return nil
	}
	out := new(KollectTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KollectTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectTargetSpec) DeepCopyInto(out *KollectTargetSpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.CollectionFilterSpec.DeepCopyInto(&out.CollectionFilterSpec)
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectTargetSpec.
func (in *KollectTargetSpec) DeepCopy() *KollectTargetSpec {
	if in == nil {
		return nil
	}
	out := new(KollectTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KollectTargetStatus) DeepCopyInto(out *KollectTargetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CollectionFilterStatus.DeepCopyInto(&out.CollectionFilterStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KollectTargetStatus.
func (in *KollectTargetStatus) DeepCopy() *KollectTargetStatus {
	if in == nil {
		return nil
	}
	out := new(KollectTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayoutFilenameSpec) DeepCopyInto(out *LayoutFilenameSpec) {
	*out = *in
	if in.LowercaseKind != nil {
		in, out := &in.LowercaseKind, &out.LowercaseKind
		*out = new(bool)
		**out = **in
	}
	if in.MaxSegmentLength != nil {
		in, out := &in.MaxSegmentLength, &out.MaxSegmentLength
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayoutFilenameSpec.
func (in *LayoutFilenameSpec) DeepCopy() *LayoutFilenameSpec {
	if in == nil {
		return nil
	}
	out := new(LayoutFilenameSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayoutIndexSpec) DeepCopyInto(out *LayoutIndexSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayoutIndexSpec.
func (in *LayoutIndexSpec) DeepCopy() *LayoutIndexSpec {
	if in == nil {
		return nil
	}
	out := new(LayoutIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayoutSpec) DeepCopyInto(out *LayoutSpec) {
	*out = *in
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(LayoutIndexSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(LayoutFilenameSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayoutSpec.
func (in *LayoutSpec) DeepCopy() *LayoutSpec {
	if in == nil {
		return nil
	}
	out := new(LayoutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeRequestSpec) DeepCopyInto(out *MergeRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeRequestSpec.
func (in *MergeRequestSpec) DeepCopy() *MergeRequestSpec {
	if in == nil {
		return nil
	}
	out := new(MergeRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSpec) DeepCopyInto(out *MetricSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSpec.
func (in *MetricSpec) DeepCopy() *MetricSpec {
	if in == nil {
		return nil
	}
	out := new(MetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBPreviewStatus) DeepCopyInto(out *MongoDBPreviewStatus) {
	*out = *in
	if in.ExpectedIndexKeys != nil {
		in, out := &in.ExpectedIndexKeys, &out.ExpectedIndexKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBPreviewStatus.
func (in *MongoDBPreviewStatus) DeepCopy() *MongoDBPreviewStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBPreviewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoSpec) DeepCopyInto(out *MongoSpec) {
	*out = *in
	if in.DatabaseRef != nil {
		in, out := &in.DatabaseRef, &out.DatabaseRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoSpec.
func (in *MongoSpec) DeepCopy() *MongoSpec {
	if in == nil {
		return nil
	}
	out := new(MongoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsSpec) DeepCopyInto(out *NatsSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsSpec.
func (in *NatsSpec) DeepCopy() *NatsSpec {
	if in == nil {
		return nil
	}
	out := new(NatsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreSpec) DeepCopyInto(out *ObjectStoreSpec) {
	*out = *in
	if in.HotAttributes != nil {
		in, out := &in.HotAttributes, &out.HotAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreSpec.
func (in *ObjectStoreSpec) DeepCopy() *ObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresPreviewStatus) DeepCopyInto(out *PostgresPreviewStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresPreviewStatus.
func (in *PostgresPreviewStatus) DeepCopy() *PostgresPreviewStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresPreviewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresSpec) DeepCopyInto(out *PostgresSpec) {
	*out = *in
	if in.DatabaseRef != nil {
		in, out := &in.DatabaseRef, &out.DatabaseRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresSpec.
func (in *PostgresSpec) DeepCopy() *PostgresSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningNamingSpec) DeepCopyInto(out *ProvisioningNamingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningNamingSpec.
func (in *ProvisioningNamingSpec) DeepCopy() *ProvisioningNamingSpec {
	if in == nil {
		return nil
	}
	out := new(ProvisioningNamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningSpec) DeepCopyInto(out *ProvisioningSpec) {
	*out = *in
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(ProvisioningNamingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningSpec.
func (in *ProvisioningSpec) DeepCopy() *ProvisioningSpec {
	if in == nil {
		return nil
	}
	out := new(ProvisioningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PruneSpec) DeepCopyInto(out *PruneSpec) {
	*out = *in
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(bool)
		**out = **in
	}
	if in.JSONPointers != nil {
		in, out := &in.JSONPointers, &out.JSONPointers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JSONPaths != nil {
		in, out := &in.JSONPaths, &out.JSONPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ScrubKeys != nil {
		in, out := &in.ScrubKeys, &out.ScrubKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CEL != nil {
		in, out := &in.CEL, &out.CEL
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PruneSpec.
func (in *PruneSpec) DeepCopy() *PruneSpec {
	if in == nil {
		return nil
	}
	out := new(PruneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRule) DeepCopyInto(out *ResourceRule) {
	*out = *in
	out.GVK = in.GVK
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]v1.LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRule.
func (in *ResourceRule) DeepCopy() *ResourceRule {
	if in == nil {
		return nil
	}
	out := new(ResourceRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeCeilingSpec) DeepCopyInto(out *ScopeCeilingSpec) {
	*out = *in
	if in.AllowedGVKs != nil {
		in, out := &in.AllowedGVKs, &out.AllowedGVKs
		*out = make([]GroupVersionKind, len(*in))
		copy(*out, *in)
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeniedNamespaces != nil {
		in, out := &in.DeniedNamespaces, &out.DeniedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinExportInterval != nil {
		in, out := &in.MinExportInterval, &out.MinExportInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeCeilingSpec.
func (in *ScopeCeilingSpec) DeepCopy() *ScopeCeilingSpec {
	if in == nil {
		return nil
	}
	out := new(ScopeCeilingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SerializationSpec) DeepCopyInto(out *SerializationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SerializationSpec.
func (in *SerializationSpec) DeepCopy() *SerializationSpec {
	if in == nil {
		return nil
	}
	out := new(SerializationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SinkCommonFields) DeepCopyInto(out *SinkCommonFields) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionTest != nil {
		in, out := &in.ConnectionTest, &out.ConnectionTest
		*out = new(bool)
		**out = **in
	}
	if in.ExportMinInterval != nil {
		in, out := &in.ExportMinInterval, &out.ExportMinInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Serialization != nil {
		in, out := &in.Serialization, &out.Serialization
		*out = new(SerializationSpec)
		**out = **in
	}
	if in.Layout != nil {
		in, out := &in.Layout, &out.Layout
		*out = new(LayoutSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Provisioning != nil {
		in, out := &in.Provisioning, &out.Provisioning
		*out = new(ProvisioningSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SinkCommonFields.
func (in *SinkCommonFields) DeepCopy() *SinkCommonFields {
	if in == nil {
		return nil
	}
	out := new(SinkCommonFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SinkPreviewStatus) DeepCopyInto(out *SinkPreviewStatus) {
	*out = *in
	if in.RenderedAt != nil {
		in, out := &in.RenderedAt, &out.RenderedAt
		*out = (*in).DeepCopy()
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitPreviewStatus)
		**out = **in
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresPreviewStatus)
		**out = **in
	}
	if in.MongoDB != nil {
		in, out := &in.MongoDB, &out.MongoDB
		*out = new(MongoDBPreviewStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaPreviewStatus)
		**out = **in
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SinkPreviewStatus.
func (in *SinkPreviewStatus) DeepCopy() *SinkPreviewStatus {
	if in == nil {
		return nil
	}
	out := new(SinkPreviewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.CABundle != nil {
		in, out := &in.CABundle, &out.CABundle
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}
