# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Konrad Heimel
---
apiVersion: v1
kind: Service
metadata:
  name: storefront-demo
  namespace: default
  labels:
    app.kubernetes.io/name: storefront
    app.kubernetes.io/part-of: demo-fleet
spec:
  selector:
    app.kubernetes.io/name: storefront
  ports:
    - port: 80
      targetPort: 80
