name: E2E (optional)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: ./.github/actions/go-cache
        with:
          envtest: true
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.51.1
      - name: Run e2e tests
        run: task test:e2e
        env:
          CI: "true"
